services:
  proyect_manager:
    image: postgres:17.5
    container_name: proyect_manager
    restart: always
    environment:
      POSTGRES_DB: proyectmanagerdb
      POSTGRES_USER: proyectmanageruser
      POSTGRES_PASSWORD: securepasword
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432